### ISSUE TITLE
File Structure being incorrectly added to DB

### ISSUE THREAD

**Issue by Kaan0200** [Kaan0200/Zoodevio_VideoLibrary#2]
Currently, what happens is you select a file to be the root.  Stuff happens.  And the database gets all the folders added correctly.  However, the entries in the table are incorrect.  The "Parent ID" field is always being set to '0' except for the parent folder which is correctly being set at -1.

Likely application side problem.

**Comment by frogsquire** [comment]
I am investigating this now. Will report back.

**Comment by frogsquire** [comment]
What is the intended behavior? Is it that, when setting up a library, parent_id for each folder should be that folder's parent on disk (at least initially)? 

So if I have a folder structure as follows:

Root Folder
--Folder 1
---Folder 2
--Folder 3

Then root is id 0, folder 1 is id 1, folder 2 is id 3, folder 3 is id 2 (suppose). 

Then root folder has parent -1, folders 1 and 3 have parent 0, folder 2 has parent 1? 

If so, should be easy to fix - please confirm.

**Comment by Kaan0200** [comment]
yes, that seems correct.

**Comment by frogsquire** [comment]
Found the problem: The folder isn't added to the database before its children are added, so it has no ID yet. Therefore, the ID is being returned as zero, because in a Folder object which didn't come from the database, it _is_ zero. 

I'm not sure how to fix this. The problem is that we don't necessarily want to be telling the database what IDs it should use, since ID is autoincrement. This is probably something for Harry to fix, but one thing we could do is this: Whenever a folder is added, add it to the database right away with all its video files. Then, get that folder's ID back FROM the database, update the folder object with it, and then move on. 

That requires a fair amount of extra DB reads, but would fix the problem.

Suggestions on alternate ways would be welcome/

**Comment by frogsquire** [comment]
Harry suggests modifying the Response enum into an object that contains some of the data that was put in the DB as a way to avoid redundant calls to the database. This sounds like a good idea, so I'll make that change and Harry will do controller-side changes to fix this.

**Comment by Kaan0200** [comment]
This is fixed.
